### ISSUE TITLE
Error on starting adsbcot -c config.ini

### ISSUE THREAD

**Issue by Tissy** [ampledata/adsbcot#14]
This error is presenting on running **DEBUG=1 adsbcot -c config.ini**

![Screenshot 2022-05-10 143757](https://user-images.githubusercontent.com/1116396/167641787-76d58511-da43-4ee2-939e-870487320a74.jpg)

Am I missing a dependency perhaps?

**Comment by ampledata** [comment]
Ensure your COT_URL has a fully formed URL, i.e. "udp://" or "tcp://"

**Comment by Tissy** [comment]
Corrected the URL, still seem to be getting the following error Greg.

![screenshot](https://user-images.githubusercontent.com/1116396/167660694-9a0f8fa5-675d-4ed3-8636-d126ec95894e.jpg)

**Comment by ampledata** [comment]
Can you paste your config

**Comment by Tissy** [comment]
Sure...

[adsbcot]
COT_URL = tcp://xx.xx.xx.xx:8087
DUMP1090_URL = tcp+beast://192.168.1.164:30005

**Comment by Tissy** [comment]
OK, figured it out.  Correct format of config.ini is...

[adsbcot]
COT_URL = tcp://xx.xx.xx.xx:8087
DUMP1090_URL = tcp+beast:192.168.1.164:30005

No // on DUMP1090_URL line

**Comment by ampledata** [comment]
Ok. I'll try to ensure the format of both urls is uniform in the future

**Comment by Tissy** [comment]
Don't worry mate, it's all good.
