### ISSUE TITLE
pytak no CoTWorker Attribute

### ISSUE THREAD

**Issue by B08Z** [ampledata/adsbcot#3]
Fresh install of adsbcot (after also installing asdbxcot)
Seems changes in pyTAK have resulted in breaking adsbcot

**Command:**
adsbcot -U 127.0.0.1:8087 -D tcp+beast:127.0.0.1:30005

**Output:**
File "/home/tak/.local/lib/python3.8/site-packages/adsbcot/commands.py", line 67, in cli
    pytak.CoTWorker(
AttributeError: module 'pytak' has no attribute 'CoTWorker'

**Comment by ampledata** [comment]
Ah yeah, good catch, will fix, thanks for the heads-up.
