### ISSUE TITLE
known_craft configuration using json possible?

### ISSUE THREAD

**Issue by robeweber** [ampledata/adsbcot#47]
Hi,
I am running a PiAware installation on a Raspi and have installed adsbcot to sent detected airplanes to my own TAK server on a different machine. This works flawlessly so far.

I see that there is the option to use known_craft.csv but can find little documentation or examples online.

While searching how best to use this option to better categorize the spotted craft, I came across the following git:
[TAK-ADSB-ID](https://github.com/sgofferj/TAK-ADSB-ID)

There, an extensive known_craft json is being built based on the creator and other user contributions per country. The documentation on how to integrate this with adsbcot is however not conclusive enough for me to know how to implement this.

Can you confirm that the json is an option in the known_craft config parameter?

I have tried:
```
[adsbcot]
COT_URL = tcp://[**localIP**]:[**port**]
FEED_URL = http://localhost:8080/data/aircraft.json
POLL_INTERVAL = 10
KNOWN_CRAFT = /home/pi/cotdb_indexed.json
```

There are not a lot of planes flying over my remote site, so I am not sure if it works like that.
Thank you for a headsup.

**Comment by robeweber** [comment]
I was wrong. There is no problem with the known_craft configuration.
I wrongly assumed that the other git repository mentioned above is plug and play. That is not the case.
When playing with different options, I reverted back to the one and only example I could find online. It is part of yet another repo [adsbxcot](https://github.com/snstac/adsbxcot).

This example csv is by no means perfect, as it even contains duplicate column names. But it works.
By using the creation script of the TAK-ADSB-ID repo mentioned above, and using the interim tmp.txt file that is being created, I have converted it to a csv instead of a json and added the header row from adsbxcot. You will need to tweak the fields in the output to match the respective header as the order of fields per record is different.

I now have 5000+ known craft that my TAK server can show with the correct COT definitions and icons.

When using the known_craft option in the ini config file, consider also the "INCLUDE_ALL_CRAFT" option. It is set to False by default and will then only show the known_craft in TAK. If you want all craft to show, even those that are not identified, set this option and define it as True.

Also, check that your output is literally using comma (,) as the delimiter, and not semicolon (;) like what excel is doing by default in my region. It only works with commas.

Thought I wanted to share my findings as there is little information online that helps.

**Comment by robeweber** [comment]
There are many ADSB TAK related repos. One is referring to the other and back again. I have not found a good tutorial so that I can combine all the features into a working and controllable setup. Finding the right combination and configuration to work for you can be challenging, and I yet have to find how all of these repos work in unison. But this issue is not an issue and I will close it.

**Comment by sgofferj** [comment]
As mentioned in https://github.com/sgofferj/TAK-ADSB-ID/issues/2, @ampledata has added support for my database into https://github.com/snstac/aircot which is a library used in adsbcot. I suppose, he hasn't had the time to add it to the documentation yet.
